#ifndef _UT_CSTL_ALGO_MUTATING_PRIVATE_H_
#define _UT_CSTL_ALGO_MUTATING_PRIVATE_H_

UT_SUIT_DECLARATION(cstl_algo_mutating_private)

#define UT_CSTL_ALGO_MUTATING_PRIVATE_CASE\

#endif /* _UT_CSTL_ALGO_MUTATING_PRIVATE_H_ */

