#ifndef _UT_CSTL_BASIC_STRING_PRIVATE_H_
#define _UT_CSTL_BASIC_STRING_PRIVATE_H_

UT_SUIT_DECLARATION(cstl_basic_string_private)

/*
 * test _create_basic_string
 */
UT_CASE_DECLARATION(_create_basic_string)
void test__create_basic_string__null_typename(void** state);
void test__create_basic_string__unregisted_type(void** state);
void test__create_basic_string__c_builtin_type(void** state);
void test__create_basic_string__libcstl_builtin_type(void** state);
void test__create_basic_string__registed_type(void** state);
/*
 * test _create_basic_string_auxiliary
 */
UT_CASE_DECLARATION(_create_basic_string_auxiliary)
void test__create_basic_string_auxiliary__null_basic_string_container(void** state);
void test__create_basic_string_auxiliary__null_typename(void** state);
void test__create_basic_string_auxiliary__unregisted_type(void** state);
void test__create_basic_string_auxiliary__c_builtin_type(void** state);
void test__create_basic_string_auxiliary__libcstl_builtin_type(void** state);
void test__create_basic_string_auxiliary__registed_type(void** state);
/*
 * test _basic_string_init_elem and _basic_string_init_elem_varg
 */
UT_CASE_DECLARATION(_basic_string_init_elem__basic_string_init_elem_varg)
void test__basic_string_init_elem__basic_string_init_elem_varg__null_basic_string_container(void** state);
void test__basic_string_init_elem__basic_string_init_elem_varg__non_created(void** state);
void test__basic_string_init_elem__basic_string_init_elem_varg__successfully_0_count(void** state);
void test__basic_string_init_elem__basic_string_init_elem_varg__successfully(void** state);
void test__basic_string_init_elem__basic_string_init_elem_varg__successfully_large_amounts_of_data(void** state);
void test__basic_string_init_elem__basic_string_init_elem_varg__successfully_multiple_specificed_element(void** state);
/*
 * test _basic_string_destroy_auxiliary
 */
UT_CASE_DECLARATION(_basic_string_destroy_auxiliary)
void test__basic_string_destroy_auxiliary__null_basic_string_container(void** state);
void test__basic_string_destroy_auxiliary__invalid_basic_string_container_finish_less_than_start(void** state);
void test__basic_string_destroy_auxiliary__invalid_basic_string_container_endofstorage_less_than_start(void** state);
void test__basic_string_destroy_auxiliary__successfully_non_init_container(void** state);
void test__basic_string_destroy_auxiliary__successfully_empty_container(void** state);
void test__basic_string_destroy_auxiliary__successfully(void** state);
/*
 * test _basic_string_find_elem and _basic_string_find_elem_varg
 */
UT_CASE_DECLARATION(_basic_string_find_elem__basic_string_find_elem_varg)
void test__basic_string_find_elem__basic_string_find_elem_varg__null_basic_string_container(void** state);
void test__basic_string_find_elem__basic_string_find_elem_varg__non_init_basic_string_container(void** state);
void test__basic_string_find_elem__basic_string_find_elem_varg__invalid_position(void** state);
void test__basic_string_find_elem__basic_string_find_elem_varg__invalid_position_end(void** state);
void test__basic_string_find_elem__basic_string_find_elem_varg__invalid_position_NPOS(void** state);
void test__basic_string_find_elem__basic_string_find_elem_varg__find_failure(void** state);
void test__basic_string_find_elem__basic_string_find_elem_varg__find_failure_middle_pos(void** state);
void test__basic_string_find_elem__basic_string_find_elem_varg__find_successful(void** state);
void test__basic_string_find_elem__basic_string_find_elem_varg__find_successful_middle(void** state);
void test__basic_string_find_elem__basic_string_find_elem_varg__find_successful_back(void** state);
void test__basic_string_find_elem__basic_string_find_elem_varg__find_successful_middle_pos(void** state);
void test__basic_string_find_elem__basic_string_find_elem_varg__cstr_find_failure(void** state);
void test__basic_string_find_elem__basic_string_find_elem_varg__cstr_find_failure_middle_pos(void** state);
void test__basic_string_find_elem__basic_string_find_elem_varg__cstr_find_successful(void** state);
void test__basic_string_find_elem__basic_string_find_elem_varg__cstr_find_successful_middle(void** state);
void test__basic_string_find_elem__basic_string_find_elem_varg__cstr_find_successful_back(void** state);
void test__basic_string_find_elem__basic_string_find_elem_varg__cstr_find_successful_middle_pos(void** state);
/*
 * test _basic_string_rfind_elem and _basic_string_rfind_elem_varg
 */
UT_CASE_DECLARATION(_basic_string_rfind_elem__basic_string_rfind_elem_varg)
void test__basic_string_rfind_elem__basic_string_rfind_elem_varg__null_basic_string_container(void** state);
void test__basic_string_rfind_elem__basic_string_rfind_elem_varg__non_init_basic_string_container(void** state);
void test__basic_string_rfind_elem__basic_string_rfind_elem_varg__invalid_position(void** state);
void test__basic_string_rfind_elem__basic_string_rfind_elem_varg__invalid_position_begin(void** state);
void test__basic_string_rfind_elem__basic_string_rfind_elem_varg__invalid_position_NPOS(void** state);
void test__basic_string_rfind_elem__basic_string_rfind_elem_varg__find_failure(void** state);
void test__basic_string_rfind_elem__basic_string_rfind_elem_varg__find_failure_middle_pos(void** state);
void test__basic_string_rfind_elem__basic_string_rfind_elem_varg__find_successful(void** state);
void test__basic_string_rfind_elem__basic_string_rfind_elem_varg__find_successful_middle(void** state);
void test__basic_string_rfind_elem__basic_string_rfind_elem_varg__find_successful_back(void** state);
void test__basic_string_rfind_elem__basic_string_rfind_elem_varg__find_successful_middle_pos(void** state);
void test__basic_string_rfind_elem__basic_string_rfind_elem_varg__cstr_find_failure(void** state);
void test__basic_string_rfind_elem__basic_string_rfind_elem_varg__cstr_find_failure_middle_pos(void** state);
void test__basic_string_rfind_elem__basic_string_rfind_elem_varg__cstr_find_successful(void** state);
void test__basic_string_rfind_elem__basic_string_rfind_elem_varg__cstr_find_successful_middle(void** state);
void test__basic_string_rfind_elem__basic_string_rfind_elem_varg__cstr_find_successful_back(void** state);
void test__basic_string_rfind_elem__basic_string_rfind_elem_varg__cstr_find_successful_middle_pos(void** state);
/*
 * test _basic_string_find_first_not_of_elem and _basic_string_find_first_not_of_elem_varg
 */
UT_CASE_DECLARATION(_basic_string_find_first_not_of_elem__basic_string_find_first_not_of_elem_varg)
void test__basic_string_find_first_not_of_elem__basic_string_find_first_not_of_elem_varg__null_basic_string_container(void** state);
void test__basic_string_find_first_not_of_elem__basic_string_find_first_not_of_elem_varg__non_init_basic_string_container(void** state);
void test__basic_string_find_first_not_of_elem__basic_string_find_first_not_of_elem_varg__invalid_position(void** state);
void test__basic_string_find_first_not_of_elem__basic_string_find_first_not_of_elem_varg__invalid_position_end(void** state);
void test__basic_string_find_first_not_of_elem__basic_string_find_first_not_of_elem_varg__invalid_position_NPOS(void** state);
void test__basic_string_find_first_not_of_elem__basic_string_find_first_not_of_elem_varg__find_first_not_of_failure(void** state);
void test__basic_string_find_first_not_of_elem__basic_string_find_first_not_of_elem_varg__find_first_not_of_failure_middle_pos(void** state);
void test__basic_string_find_first_not_of_elem__basic_string_find_first_not_of_elem_varg__find_first_not_of_successful(void** state);
void test__basic_string_find_first_not_of_elem__basic_string_find_first_not_of_elem_varg__find_first_not_of_successful_middle(void** state);
void test__basic_string_find_first_not_of_elem__basic_string_find_first_not_of_elem_varg__find_first_not_of_successful_back(void** state);
void test__basic_string_find_first_not_of_elem__basic_string_find_first_not_of_elem_varg__find_first_not_of_successful_middle_pos(void** state);
void test__basic_string_find_first_not_of_elem__basic_string_find_first_not_of_elem_varg__cstr_find_first_not_of_failure(void** state);
void test__basic_string_find_first_not_of_elem__basic_string_find_first_not_of_elem_varg__cstr_find_first_not_of_failure_middle_pos(void** state);
void test__basic_string_find_first_not_of_elem__basic_string_find_first_not_of_elem_varg__cstr_find_first_not_of_successful(void** state);
void test__basic_string_find_first_not_of_elem__basic_string_find_first_not_of_elem_varg__cstr_find_first_not_of_successful_middle(void** state);
void test__basic_string_find_first_not_of_elem__basic_string_find_first_not_of_elem_varg__cstr_find_first_not_of_successful_back(void** state);
void test__basic_string_find_first_not_of_elem__basic_string_find_first_not_of_elem_varg__cstr_find_first_not_of_successful_middle_pos(void** state);
/*
 * test _basic_string_find_last_not_of_elem and _basic_string_find_last_not_of_elem_varg
 */
UT_CASE_DECLARATION(_basic_string_find_last_not_of_elem__basic_string_find_last_not_of_elem_varg)
void test__basic_string_find_last_not_of_elem__basic_string_find_last_not_of_elem_varg__null_basic_string_container(void** state);
void test__basic_string_find_last_not_of_elem__basic_string_find_last_not_of_elem_varg__non_init_basic_string_container(void** state);
void test__basic_string_find_last_not_of_elem__basic_string_find_last_not_of_elem_varg__invalid_position(void** state);
void test__basic_string_find_last_not_of_elem__basic_string_find_last_not_of_elem_varg__invalid_position_begin(void** state);
void test__basic_string_find_last_not_of_elem__basic_string_find_last_not_of_elem_varg__invalid_position_NPOS(void** state);
void test__basic_string_find_last_not_of_elem__basic_string_find_last_not_of_elem_varg__find_failure(void** state);
void test__basic_string_find_last_not_of_elem__basic_string_find_last_not_of_elem_varg__find_failure_middle_pos(void** state);
void test__basic_string_find_last_not_of_elem__basic_string_find_last_not_of_elem_varg__find_successful(void** state);
void test__basic_string_find_last_not_of_elem__basic_string_find_last_not_of_elem_varg__find_successful_middle(void** state);
void test__basic_string_find_last_not_of_elem__basic_string_find_last_not_of_elem_varg__find_successful_back(void** state);
void test__basic_string_find_last_not_of_elem__basic_string_find_last_not_of_elem_varg__find_successful_middle_pos(void** state);
void test__basic_string_find_last_not_of_elem__basic_string_find_last_not_of_elem_varg__cstr_find_failure(void** state);
void test__basic_string_find_last_not_of_elem__basic_string_find_last_not_of_elem_varg__cstr_find_failure_middle_pos(void** state);
void test__basic_string_find_last_not_of_elem__basic_string_find_last_not_of_elem_varg__cstr_find_successful(void** state);
void test__basic_string_find_last_not_of_elem__basic_string_find_last_not_of_elem_varg__cstr_find_successful_middle(void** state);
void test__basic_string_find_last_not_of_elem__basic_string_find_last_not_of_elem_varg__cstr_find_successful_back(void** state);
void test__basic_string_find_last_not_of_elem__basic_string_find_last_not_of_elem_varg__cstr_find_successful_middle_pos(void** state);
/*
 * test _basic_string_connect_elem and _basic_string_connect_elem_varg
 */
UT_CASE_DECLARATION(_basic_string_connect_elem__basic_string_connect_elem_varg)
void test__basic_string_connect_elem__basic_string_connect_elem_varg__null_basic_string_container(void** state);
void test__basic_string_connect_elem__basic_string_connect_elem_varg__non_inited_basic_string_container(void** state);
void test__basic_string_connect_elem__basic_string_connect_elem_varg__empty_container(void** state);
void test__basic_string_connect_elem__basic_string_connect_elem_varg__non_empty_container(void** state);
void test__basic_string_connect_elem__basic_string_connect_elem_varg__cstr_empty_container(void** state);
void test__basic_string_connect_elem__basic_string_connect_elem_varg__cstr_non_empty_container(void** state);
/*
 * test _basic_string_assign_elem and _basic_string_assign_elem_varg
 */
UT_CASE_DECLARATION(_basic_string_assign_elem__basic_string_assign_elem_varg)
void test__basic_string_assign_elem__basic_string_assign_elem_varg__null_container(void** state);
void test__basic_string_assign_elem__basic_string_assign_elem_varg__non_inited_container(void** state);
void test__basic_string_assign_elem__basic_string_assign_elem_varg__empty_container_assign_empty(void** state);
void test__basic_string_assign_elem__basic_string_assign_elem_varg__empty_container_assign_non_empty(void** state);
void test__basic_string_assign_elem__basic_string_assign_elem_varg__non_empty_container_assign_empty(void** state);
void test__basic_string_assign_elem__basic_string_assign_elem_varg__non_empty_container_assign_less(void** state);
void test__basic_string_assign_elem__basic_string_assign_elem_varg__non_empty_container_assign_equal(void** state);
void test__basic_string_assign_elem__basic_string_assign_elem_varg__non_empty_container_assign_greater(void** state);
void test__basic_string_assign_elem__basic_string_assign_elem_varg__cstr_empty_container_assign_empty(void** state);
void test__basic_string_assign_elem__basic_string_assign_elem_varg__cstr_empty_container_assign_non_empty(void** state);
void test__basic_string_assign_elem__basic_string_assign_elem_varg__cstr_non_empty_container_assign_empty(void** state);
void test__basic_string_assign_elem__basic_string_assign_elem_varg__cstr_non_empty_container_assign_less(void** state);
void test__basic_string_assign_elem__basic_string_assign_elem_varg__cstr_non_empty_container_assign_equal(void** state);
void test__basic_string_assign_elem__basic_string_assign_elem_varg__cstr_non_empty_container_assign_greater(void** state);
/*
 * test _basic_string_push_back and _basic_string_push_back_varg
 */
UT_CASE_DECLARATION(_basic_string_push_back__basic_string_push_back_varg)
void test__basic_string_push_back__basic_string_push_back_varg__null_container(void** state);
void test__basic_string_push_back__basic_string_push_back_varg__non_inited_container(void** state);
void test__basic_string_push_back__basic_string_push_back_varg__empty(void** state);
void test__basic_string_push_back__basic_string_push_back_varg__non_empty(void** state);
void test__basic_string_push_back__basic_string_push_back_varg__cstr_empty(void** state);
void test__basic_string_push_back__basic_string_push_back_varg__cstr_non_empty(void** state);
/*
 * test _basic_string_pop_back
 */
UT_CASE_DECLARATION(_basic_string_pop_back)
void test__basic_string_pop_back__null_container(void** state);
void test__basic_string_pop_back__non_inited_container(void** state);
void test__basic_string_pop_back__empty(void** state);
void test__basic_string_pop_back__non_empty(void** state);
void test__basic_string_pop_back__cstr_non_empty(void** state);
/*
 * test _basic_string_resize and _basic_string_resize_varg
 */
UT_CASE_DECLARATION(_basic_string_resize__basic_string_resize_varg)
void test__basic_string_resize__basic_string_resize_varg__null_basic_string_container(void** state);
void test__basic_string_resize__basic_string_resize_varg__non_inited(void** state);
void test__basic_string_resize__basic_string_resize_varg__successfully_0_resize_0(void** state);
void test__basic_string_resize__basic_string_resize_varg__successfully_0_resize_10(void** state);
void test__basic_string_resize__basic_string_resize_varg__successfully_0_resize_1000(void** state);
void test__basic_string_resize__basic_string_resize_varg__successfully_10_resize_0(void** state);
void test__basic_string_resize__basic_string_resize_varg__successfully_10_resize_10(void** state);
void test__basic_string_resize__basic_string_resize_varg__successfully_10_resize_1000(void** state);
void test__basic_string_resize__basic_string_resize_varg__successfully_1000_resize_0(void** state);
void test__basic_string_resize__basic_string_resize_varg__successfully_1000_resize_10(void** setate);
void test__basic_string_resize__basic_string_resize_varg__successfully_1000_resize_1000(void** state);
void test__basic_string_resize__basic_string_resize_varg__successfully_1000_resize_1200(void** state);
void test__basic_string_resize__basic_string_resize_varg__successfully_1000_resize_2000(void** state);
void test__basic_string_resize__basic_string_resize_varg__successfully_1000_resize_2000_multiple(void** state);
/*
 * test _basic_string_append_elem and _basic_string_append_elem_varg
 */
UT_CASE_DECLARATION(_basic_string_append_elem__basic_string_append_elem_varg)
void test__basic_string_append_elem__basic_string_append_elem_varg__null_container(void** state);
void test__basic_string_append_elem__basic_string_append_elem_varg__non_inited_container(void** state);
void test__basic_string_append_elem__basic_string_append_elem_varg__empty_append_empty(void** state);
void test__basic_string_append_elem__basic_string_append_elem_varg__empty_append_non_empty(void** state);
void test__basic_string_append_elem__basic_string_append_elem_varg__non_empty_append_empty(void** state);
void test__basic_string_append_elem__basic_string_append_elem_varg__non_empty_append_non_empty(void** state);
void test__basic_string_append_elem__basic_string_append_elem_varg__cstr_empty_append_empty(void** state);
void test__basic_string_append_elem__basic_string_append_elem_varg__cstr_empty_append_non_empty(void** state);
void test__basic_string_append_elem__basic_string_append_elem_varg__cstr_non_empty_append_empty(void** state);
void test__basic_string_append_elem__basic_string_append_elem_varg__cstr_non_empty_append_non_empty(void** state);
/*
 * test _basic_string_insert_n and _basic_string_insert_n_varg
 */
UT_CASE_DECLARATION(_basic_string_insert_n__basic_string_insert_n_varg)
void test__basic_string_insert_n__basic_string_insert_n_varg__null_basic_string_container(void** state);
void test__basic_string_insert_n__basic_string_insert_n_varg__non_inited(void** state);
void test__basic_string_insert_n__basic_string_insert_n_varg__invalid_position(void** state);
void test__basic_string_insert_n__basic_string_insert_n_varg__empty_insert_0(void** state);
void test__basic_string_insert_n__basic_string_insert_n_varg__empty_insert_10(void** state);
void test__basic_string_insert_n__basic_string_insert_n_varg__empty_insert_1000(void** state);
void test__basic_string_insert_n__basic_string_insert_n_varg__begin_insert_0(void** state);
void test__basic_string_insert_n__basic_string_insert_n_varg__begin_insert_10(void** state);
void test__basic_string_insert_n__basic_string_insert_n_varg__begin_insert_1000(void** state);
void test__basic_string_insert_n__basic_string_insert_n_varg__middle_insert_0(void** state);
void test__basic_string_insert_n__basic_string_insert_n_varg__middle_insert_10(void** state);
void test__basic_string_insert_n__basic_string_insert_n_varg__middle_insert_1000(void** state);
void test__basic_string_insert_n__basic_string_insert_n_varg__end_insert_0(void** state);
void test__basic_string_insert_n__basic_string_insert_n_varg__end_insert_10(void** state);
void test__basic_string_insert_n__basic_string_insert_n_varg__end_insert_1000(void** state);
void test__basic_string_insert_n__basic_string_insert_n_varg__end_insert_1000_multiple(void** state);
/*
 * test _basic_string_insert_elem and _basic_string_insert_elem_varg
 */
UT_CASE_DECLARATION(_basic_string_insert_elem__basic_string_insert_elem_varg)
void test__basic_string_insert_elem__basic_string_insert_elem_varg__null_basic_string_container(void** state);
void test__basic_string_insert_elem__basic_string_insert_elem_varg__non_inited(void** state);
void test__basic_string_insert_elem__basic_string_insert_elem_varg__invalid_position(void** state);
void test__basic_string_insert_elem__basic_string_insert_elem_varg__empty_insert_0(void** state);
void test__basic_string_insert_elem__basic_string_insert_elem_varg__empty_insert_10(void** state);
void test__basic_string_insert_elem__basic_string_insert_elem_varg__empty_insert_1000(void** state);
void test__basic_string_insert_elem__basic_string_insert_elem_varg__begin_insert_0(void** state);
void test__basic_string_insert_elem__basic_string_insert_elem_varg__begin_insert_10(void** state);
void test__basic_string_insert_elem__basic_string_insert_elem_varg__begin_insert_1000(void** state);
void test__basic_string_insert_elem__basic_string_insert_elem_varg__middle_insert_0(void** state);
void test__basic_string_insert_elem__basic_string_insert_elem_varg__middle_insert_10(void** state);
void test__basic_string_insert_elem__basic_string_insert_elem_varg__middle_insert_1000(void** state);
void test__basic_string_insert_elem__basic_string_insert_elem_varg__end_insert_0(void** state);
void test__basic_string_insert_elem__basic_string_insert_elem_varg__end_insert_10(void** state);
void test__basic_string_insert_elem__basic_string_insert_elem_varg__end_insert_1000(void** state);
void test__basic_string_insert_elem__basic_string_insert_elem_varg__end_insert_1000_multiple(void** state);
/*
 * test _basic_string_range_replace_elem and _basic_string_range_replace_elem_varg
 */
UT_CASE_DECLARATION(_basic_string_range_replace_elem__basic_string_range_replace_elem_varg)
void test__basic_string_range_replace_elem__basic_string_range_replace_elem_varg__null_container(void** state);
void test__basic_string_range_replace_elem__basic_string_range_replace_elem_varg__non_inited_container(void** state);
void test__basic_string_range_replace_elem__basic_string_range_replace_elem_varg__invalid_range(void** state);
void test__basic_string_range_replace_elem__basic_string_range_replace_elem_varg__empty_replace_empty(void** state);
void test__basic_string_range_replace_elem__basic_string_range_replace_elem_varg__empty_replace_non_empty(void** state);
void test__basic_string_range_replace_elem__basic_string_range_replace_elem_varg__begin_replace_empty(void** state);
void test__basic_string_range_replace_elem__basic_string_range_replace_elem_varg__begin_replace_less(void** state);
void test__basic_string_range_replace_elem__basic_string_range_replace_elem_varg__begin_replace_equal(void** state);
void test__basic_string_range_replace_elem__basic_string_range_replace_elem_varg__begin_replace_greater(void** state);
void test__basic_string_range_replace_elem__basic_string_range_replace_elem_varg__middle_replace_empty(void** state);
void test__basic_string_range_replace_elem__basic_string_range_replace_elem_varg__middle_replace_less(void** state);
void test__basic_string_range_replace_elem__basic_string_range_replace_elem_varg__middle_replace_equal(void** state);
void test__basic_string_range_replace_elem__basic_string_range_replace_elem_varg__middle_replace_greater(void** state);
void test__basic_string_range_replace_elem__basic_string_range_replace_elem_varg__end_replace_empty(void** state);
void test__basic_string_range_replace_elem__basic_string_range_replace_elem_varg__end_replace_less(void** state);
void test__basic_string_range_replace_elem__basic_string_range_replace_elem_varg__end_replace_equal(void** state);
void test__basic_string_range_replace_elem__basic_string_range_replace_elem_varg__end_replace_greater(void** state);

#define UT_CSTL_BASIC_STRING_PRIVATE_CASE\
    UT_SUIT_BEGIN(cstl_basic_string_private, test__create_basic_string__null_typename),\
    UT_CASE(test__create_basic_string__unregisted_type),\
    UT_CASE(test__create_basic_string__c_builtin_type),\
    UT_CASE(test__create_basic_string__libcstl_builtin_type),\
    UT_CASE(test__create_basic_string__registed_type),\
    UT_CASE_BEGIN(_create_basic_string_auxiliary, test__create_basic_string_auxiliary__null_basic_string_container),\
    UT_CASE(test__create_basic_string_auxiliary__null_typename),\
    UT_CASE(test__create_basic_string_auxiliary__unregisted_type),\
    UT_CASE(test__create_basic_string_auxiliary__c_builtin_type),\
    UT_CASE(test__create_basic_string_auxiliary__libcstl_builtin_type),\
    UT_CASE(test__create_basic_string_auxiliary__registed_type),\
    UT_CASE_BEGIN(_basic_string_init_elem__basic_string_init_elem_varg,\
            test__basic_string_init_elem__basic_string_init_elem_varg__null_basic_string_container),\
    UT_CASE(test__basic_string_init_elem__basic_string_init_elem_varg__non_created),\
    UT_CASE(test__basic_string_init_elem__basic_string_init_elem_varg__successfully_0_count),\
    UT_CASE(test__basic_string_init_elem__basic_string_init_elem_varg__successfully),\
    UT_CASE(test__basic_string_init_elem__basic_string_init_elem_varg__successfully_large_amounts_of_data),\
    UT_CASE(test__basic_string_init_elem__basic_string_init_elem_varg__successfully_multiple_specificed_element),\
    UT_CASE_BEGIN(_basic_string_destroy_auxiliary, test__basic_string_destroy_auxiliary__null_basic_string_container),\
    UT_CASE(test__basic_string_destroy_auxiliary__invalid_basic_string_container_finish_less_than_start),\
    UT_CASE(test__basic_string_destroy_auxiliary__invalid_basic_string_container_endofstorage_less_than_start),\
    UT_CASE(test__basic_string_destroy_auxiliary__successfully_non_init_container),\
    UT_CASE(test__basic_string_destroy_auxiliary__successfully_empty_container),\
    UT_CASE(test__basic_string_destroy_auxiliary__successfully),\
    UT_CASE_BEGIN(_basic_string_find_elem__basic_string_find_elem_varg,\
        test__basic_string_find_elem__basic_string_find_elem_varg__null_basic_string_container),\
    UT_CASE(test__basic_string_find_elem__basic_string_find_elem_varg__non_init_basic_string_container),\
    UT_CASE(test__basic_string_find_elem__basic_string_find_elem_varg__invalid_position),\
    UT_CASE(test__basic_string_find_elem__basic_string_find_elem_varg__invalid_position_end),\
    UT_CASE(test__basic_string_find_elem__basic_string_find_elem_varg__invalid_position_NPOS),\
    UT_CASE(test__basic_string_find_elem__basic_string_find_elem_varg__find_failure),\
    UT_CASE(test__basic_string_find_elem__basic_string_find_elem_varg__find_failure_middle_pos),\
    UT_CASE(test__basic_string_find_elem__basic_string_find_elem_varg__find_successful),\
    UT_CASE(test__basic_string_find_elem__basic_string_find_elem_varg__find_successful_middle),\
    UT_CASE(test__basic_string_find_elem__basic_string_find_elem_varg__find_successful_back),\
    UT_CASE(test__basic_string_find_elem__basic_string_find_elem_varg__find_successful_middle_pos),\
    UT_CASE(test__basic_string_find_elem__basic_string_find_elem_varg__cstr_find_failure),\
    UT_CASE(test__basic_string_find_elem__basic_string_find_elem_varg__cstr_find_failure_middle_pos),\
    UT_CASE(test__basic_string_find_elem__basic_string_find_elem_varg__cstr_find_successful),\
    UT_CASE(test__basic_string_find_elem__basic_string_find_elem_varg__cstr_find_successful_middle),\
    UT_CASE(test__basic_string_find_elem__basic_string_find_elem_varg__cstr_find_successful_back),\
    UT_CASE(test__basic_string_find_elem__basic_string_find_elem_varg__cstr_find_successful_middle_pos),\
    UT_CASE_BEGIN(_basic_string_rfind_elem__basic_string_rfind_elem_varg,\
        test__basic_string_rfind_elem__basic_string_rfind_elem_varg__null_basic_string_container),\
    UT_CASE(test__basic_string_rfind_elem__basic_string_rfind_elem_varg__non_init_basic_string_container),\
    UT_CASE(test__basic_string_rfind_elem__basic_string_rfind_elem_varg__invalid_position),\
    UT_CASE(test__basic_string_rfind_elem__basic_string_rfind_elem_varg__invalid_position_begin),\
    UT_CASE(test__basic_string_rfind_elem__basic_string_rfind_elem_varg__invalid_position_NPOS),\
    UT_CASE(test__basic_string_rfind_elem__basic_string_rfind_elem_varg__find_failure),\
    UT_CASE(test__basic_string_rfind_elem__basic_string_rfind_elem_varg__find_failure_middle_pos),\
    UT_CASE(test__basic_string_rfind_elem__basic_string_rfind_elem_varg__find_successful),\
    UT_CASE(test__basic_string_rfind_elem__basic_string_rfind_elem_varg__find_successful_middle),\
    UT_CASE(test__basic_string_rfind_elem__basic_string_rfind_elem_varg__find_successful_back),\
    UT_CASE(test__basic_string_rfind_elem__basic_string_rfind_elem_varg__find_successful_middle_pos),\
    UT_CASE(test__basic_string_rfind_elem__basic_string_rfind_elem_varg__cstr_find_failure),\
    UT_CASE(test__basic_string_rfind_elem__basic_string_rfind_elem_varg__cstr_find_failure_middle_pos),\
    UT_CASE(test__basic_string_rfind_elem__basic_string_rfind_elem_varg__cstr_find_successful),\
    UT_CASE(test__basic_string_rfind_elem__basic_string_rfind_elem_varg__cstr_find_successful_middle),\
    UT_CASE(test__basic_string_rfind_elem__basic_string_rfind_elem_varg__cstr_find_successful_back),\
    UT_CASE(test__basic_string_rfind_elem__basic_string_rfind_elem_varg__cstr_find_successful_middle_pos),\
    UT_CASE_BEGIN(_basic_string_find_first_not_of_elem__basic_string_find_first_not_of_elem_varg,\
        test__basic_string_find_first_not_of_elem__basic_string_find_first_not_of_elem_varg__null_basic_string_container),\
    UT_CASE(test__basic_string_find_first_not_of_elem__basic_string_find_first_not_of_elem_varg__non_init_basic_string_container),\
    UT_CASE(test__basic_string_find_first_not_of_elem__basic_string_find_first_not_of_elem_varg__invalid_position),\
    UT_CASE(test__basic_string_find_first_not_of_elem__basic_string_find_first_not_of_elem_varg__invalid_position_end),\
    UT_CASE(test__basic_string_find_first_not_of_elem__basic_string_find_first_not_of_elem_varg__invalid_position_NPOS),\
    UT_CASE(test__basic_string_find_first_not_of_elem__basic_string_find_first_not_of_elem_varg__find_first_not_of_failure),\
    UT_CASE(test__basic_string_find_first_not_of_elem__basic_string_find_first_not_of_elem_varg__find_first_not_of_failure_middle_pos),\
    UT_CASE(test__basic_string_find_first_not_of_elem__basic_string_find_first_not_of_elem_varg__find_first_not_of_successful),\
    UT_CASE(test__basic_string_find_first_not_of_elem__basic_string_find_first_not_of_elem_varg__find_first_not_of_successful_middle),\
    UT_CASE(test__basic_string_find_first_not_of_elem__basic_string_find_first_not_of_elem_varg__find_first_not_of_successful_back),\
    UT_CASE(test__basic_string_find_first_not_of_elem__basic_string_find_first_not_of_elem_varg__find_first_not_of_successful_middle_pos),\
    UT_CASE(test__basic_string_find_first_not_of_elem__basic_string_find_first_not_of_elem_varg__cstr_find_first_not_of_failure),\
    UT_CASE(test__basic_string_find_first_not_of_elem__basic_string_find_first_not_of_elem_varg__cstr_find_first_not_of_failure_middle_pos),\
    UT_CASE(test__basic_string_find_first_not_of_elem__basic_string_find_first_not_of_elem_varg__cstr_find_first_not_of_successful),\
    UT_CASE(test__basic_string_find_first_not_of_elem__basic_string_find_first_not_of_elem_varg__cstr_find_first_not_of_successful_middle),\
    UT_CASE(test__basic_string_find_first_not_of_elem__basic_string_find_first_not_of_elem_varg__cstr_find_first_not_of_successful_back),\
    UT_CASE(test__basic_string_find_first_not_of_elem__basic_string_find_first_not_of_elem_varg__cstr_find_first_not_of_successful_middle_pos),\
    UT_CASE_BEGIN(_basic_string_find_last_not_of_elem__basic_string_find_last_not_of_elem_varg,\
        test__basic_string_find_last_not_of_elem__basic_string_find_last_not_of_elem_varg__null_basic_string_container),\
    UT_CASE(test__basic_string_find_last_not_of_elem__basic_string_find_last_not_of_elem_varg__non_init_basic_string_container),\
    UT_CASE(test__basic_string_find_last_not_of_elem__basic_string_find_last_not_of_elem_varg__invalid_position),\
    UT_CASE(test__basic_string_find_last_not_of_elem__basic_string_find_last_not_of_elem_varg__invalid_position_begin),\
    UT_CASE(test__basic_string_find_last_not_of_elem__basic_string_find_last_not_of_elem_varg__invalid_position_NPOS),\
    UT_CASE(test__basic_string_find_last_not_of_elem__basic_string_find_last_not_of_elem_varg__find_failure),\
    UT_CASE(test__basic_string_find_last_not_of_elem__basic_string_find_last_not_of_elem_varg__find_failure_middle_pos),\
    UT_CASE(test__basic_string_find_last_not_of_elem__basic_string_find_last_not_of_elem_varg__find_successful),\
    UT_CASE(test__basic_string_find_last_not_of_elem__basic_string_find_last_not_of_elem_varg__find_successful_middle),\
    UT_CASE(test__basic_string_find_last_not_of_elem__basic_string_find_last_not_of_elem_varg__find_successful_back),\
    UT_CASE(test__basic_string_find_last_not_of_elem__basic_string_find_last_not_of_elem_varg__find_successful_middle_pos),\
    UT_CASE(test__basic_string_find_last_not_of_elem__basic_string_find_last_not_of_elem_varg__cstr_find_failure),\
    UT_CASE(test__basic_string_find_last_not_of_elem__basic_string_find_last_not_of_elem_varg__cstr_find_failure_middle_pos),\
    UT_CASE(test__basic_string_find_last_not_of_elem__basic_string_find_last_not_of_elem_varg__cstr_find_successful),\
    UT_CASE(test__basic_string_find_last_not_of_elem__basic_string_find_last_not_of_elem_varg__cstr_find_successful_middle),\
    UT_CASE(test__basic_string_find_last_not_of_elem__basic_string_find_last_not_of_elem_varg__cstr_find_successful_back),\
    UT_CASE(test__basic_string_find_last_not_of_elem__basic_string_find_last_not_of_elem_varg__cstr_find_successful_middle_pos),\
    UT_CASE_BEGIN(_basic_string_connect_elem__basic_string_connect_elem_varg,\
        test__basic_string_connect_elem__basic_string_connect_elem_varg__null_basic_string_container),\
    UT_CASE(test__basic_string_connect_elem__basic_string_connect_elem_varg__non_inited_basic_string_container),\
    UT_CASE(test__basic_string_connect_elem__basic_string_connect_elem_varg__empty_container),\
    UT_CASE(test__basic_string_connect_elem__basic_string_connect_elem_varg__non_empty_container),\
    UT_CASE(test__basic_string_connect_elem__basic_string_connect_elem_varg__cstr_empty_container),\
    UT_CASE(test__basic_string_connect_elem__basic_string_connect_elem_varg__cstr_non_empty_container),\
    UT_CASE_BEGIN(_basic_string_assign_elem__basic_string_assign_elem_varg,\
        test__basic_string_assign_elem__basic_string_assign_elem_varg__null_container),\
    UT_CASE(test__basic_string_assign_elem__basic_string_assign_elem_varg__non_inited_container),\
    UT_CASE(test__basic_string_assign_elem__basic_string_assign_elem_varg__empty_container_assign_empty),\
    UT_CASE(test__basic_string_assign_elem__basic_string_assign_elem_varg__empty_container_assign_non_empty),\
    UT_CASE(test__basic_string_assign_elem__basic_string_assign_elem_varg__non_empty_container_assign_empty),\
    UT_CASE(test__basic_string_assign_elem__basic_string_assign_elem_varg__non_empty_container_assign_less),\
    UT_CASE(test__basic_string_assign_elem__basic_string_assign_elem_varg__non_empty_container_assign_equal),\
    UT_CASE(test__basic_string_assign_elem__basic_string_assign_elem_varg__non_empty_container_assign_greater),\
    UT_CASE(test__basic_string_assign_elem__basic_string_assign_elem_varg__cstr_empty_container_assign_empty),\
    UT_CASE(test__basic_string_assign_elem__basic_string_assign_elem_varg__cstr_empty_container_assign_non_empty),\
    UT_CASE(test__basic_string_assign_elem__basic_string_assign_elem_varg__cstr_non_empty_container_assign_empty),\
    UT_CASE(test__basic_string_assign_elem__basic_string_assign_elem_varg__cstr_non_empty_container_assign_less),\
    UT_CASE(test__basic_string_assign_elem__basic_string_assign_elem_varg__cstr_non_empty_container_assign_equal),\
    UT_CASE(test__basic_string_assign_elem__basic_string_assign_elem_varg__cstr_non_empty_container_assign_greater),\
    UT_CASE_BEGIN(_basic_string_push_back__basic_string_push_back_varg,\
        test__basic_string_push_back__basic_string_push_back_varg__null_container),\
    UT_CASE(test__basic_string_push_back__basic_string_push_back_varg__non_inited_container),\
    UT_CASE(test__basic_string_push_back__basic_string_push_back_varg__empty),\
    UT_CASE(test__basic_string_push_back__basic_string_push_back_varg__non_empty),\
    UT_CASE(test__basic_string_push_back__basic_string_push_back_varg__cstr_empty),\
    UT_CASE(test__basic_string_push_back__basic_string_push_back_varg__cstr_non_empty),\
    UT_CASE_BEGIN(_basic_string_pop_back, test__basic_string_pop_back__null_container),\
    UT_CASE(test__basic_string_pop_back__non_inited_container),\
    UT_CASE(test__basic_string_pop_back__empty),\
    UT_CASE(test__basic_string_pop_back__non_empty),\
    UT_CASE(test__basic_string_pop_back__cstr_non_empty),\
    UT_CASE_BEGIN(_basic_string_resize__basic_string_resize_varg,\
        test__basic_string_resize__basic_string_resize_varg__null_basic_string_container),\
    UT_CASE(test__basic_string_resize__basic_string_resize_varg__non_inited),\
    UT_CASE(test__basic_string_resize__basic_string_resize_varg__successfully_0_resize_0),\
    UT_CASE(test__basic_string_resize__basic_string_resize_varg__successfully_0_resize_10),\
    UT_CASE(test__basic_string_resize__basic_string_resize_varg__successfully_0_resize_1000),\
    UT_CASE(test__basic_string_resize__basic_string_resize_varg__successfully_10_resize_0),\
    UT_CASE(test__basic_string_resize__basic_string_resize_varg__successfully_10_resize_10),\
    UT_CASE(test__basic_string_resize__basic_string_resize_varg__successfully_10_resize_1000),\
    UT_CASE(test__basic_string_resize__basic_string_resize_varg__successfully_1000_resize_0),\
    UT_CASE(test__basic_string_resize__basic_string_resize_varg__successfully_1000_resize_10),\
    UT_CASE(test__basic_string_resize__basic_string_resize_varg__successfully_1000_resize_1000),\
    UT_CASE(test__basic_string_resize__basic_string_resize_varg__successfully_1000_resize_1200),\
    UT_CASE(test__basic_string_resize__basic_string_resize_varg__successfully_1000_resize_2000),\
    UT_CASE(test__basic_string_resize__basic_string_resize_varg__successfully_1000_resize_2000_multiple),\
    UT_CASE_BEGIN(_basic_string_append_elem__basic_string_append_elem_varg,\
        test__basic_string_append_elem__basic_string_append_elem_varg__null_container),\
    UT_CASE(test__basic_string_append_elem__basic_string_append_elem_varg__non_inited_container),\
    UT_CASE(test__basic_string_append_elem__basic_string_append_elem_varg__empty_append_empty),\
    UT_CASE(test__basic_string_append_elem__basic_string_append_elem_varg__empty_append_non_empty),\
    UT_CASE(test__basic_string_append_elem__basic_string_append_elem_varg__non_empty_append_empty),\
    UT_CASE(test__basic_string_append_elem__basic_string_append_elem_varg__non_empty_append_non_empty),\
    UT_CASE(test__basic_string_append_elem__basic_string_append_elem_varg__cstr_empty_append_empty),\
    UT_CASE(test__basic_string_append_elem__basic_string_append_elem_varg__cstr_empty_append_non_empty),\
    UT_CASE(test__basic_string_append_elem__basic_string_append_elem_varg__cstr_non_empty_append_empty),\
    UT_CASE(test__basic_string_append_elem__basic_string_append_elem_varg__cstr_non_empty_append_non_empty),\
    UT_CASE_BEGIN(_basic_string_insert_n__basic_string_insert_n_varg,\
        test__basic_string_insert_n__basic_string_insert_n_varg__null_basic_string_container),\
    UT_CASE(test__basic_string_insert_n__basic_string_insert_n_varg__non_inited),\
    UT_CASE(test__basic_string_insert_n__basic_string_insert_n_varg__invalid_position),\
    UT_CASE(test__basic_string_insert_n__basic_string_insert_n_varg__empty_insert_0),\
    UT_CASE(test__basic_string_insert_n__basic_string_insert_n_varg__empty_insert_10),\
    UT_CASE(test__basic_string_insert_n__basic_string_insert_n_varg__empty_insert_1000),\
    UT_CASE(test__basic_string_insert_n__basic_string_insert_n_varg__begin_insert_0),\
    UT_CASE(test__basic_string_insert_n__basic_string_insert_n_varg__begin_insert_10),\
    UT_CASE(test__basic_string_insert_n__basic_string_insert_n_varg__begin_insert_1000),\
    UT_CASE(test__basic_string_insert_n__basic_string_insert_n_varg__middle_insert_0),\
    UT_CASE(test__basic_string_insert_n__basic_string_insert_n_varg__middle_insert_10),\
    UT_CASE(test__basic_string_insert_n__basic_string_insert_n_varg__middle_insert_1000),\
    UT_CASE(test__basic_string_insert_n__basic_string_insert_n_varg__end_insert_0),\
    UT_CASE(test__basic_string_insert_n__basic_string_insert_n_varg__end_insert_10),\
    UT_CASE(test__basic_string_insert_n__basic_string_insert_n_varg__end_insert_1000),\
    UT_CASE(test__basic_string_insert_n__basic_string_insert_n_varg__end_insert_1000_multiple),\
    UT_CASE_BEGIN(_basic_string_insert_elem__basic_string_insert_elem_varg,\
        test__basic_string_insert_elem__basic_string_insert_elem_varg__null_basic_string_container),\
    UT_CASE(test__basic_string_insert_elem__basic_string_insert_elem_varg__non_inited),\
    UT_CASE(test__basic_string_insert_elem__basic_string_insert_elem_varg__invalid_position),\
    UT_CASE(test__basic_string_insert_elem__basic_string_insert_elem_varg__empty_insert_0),\
    UT_CASE(test__basic_string_insert_elem__basic_string_insert_elem_varg__empty_insert_10),\
    UT_CASE(test__basic_string_insert_elem__basic_string_insert_elem_varg__empty_insert_1000),\
    UT_CASE(test__basic_string_insert_elem__basic_string_insert_elem_varg__begin_insert_0),\
    UT_CASE(test__basic_string_insert_elem__basic_string_insert_elem_varg__begin_insert_10),\
    UT_CASE(test__basic_string_insert_elem__basic_string_insert_elem_varg__begin_insert_1000),\
    UT_CASE(test__basic_string_insert_elem__basic_string_insert_elem_varg__middle_insert_0),\
    UT_CASE(test__basic_string_insert_elem__basic_string_insert_elem_varg__middle_insert_10),\
    UT_CASE(test__basic_string_insert_elem__basic_string_insert_elem_varg__middle_insert_1000),\
    UT_CASE(test__basic_string_insert_elem__basic_string_insert_elem_varg__end_insert_0),\
    UT_CASE(test__basic_string_insert_elem__basic_string_insert_elem_varg__end_insert_10),\
    UT_CASE(test__basic_string_insert_elem__basic_string_insert_elem_varg__end_insert_1000),\
    UT_CASE(test__basic_string_insert_elem__basic_string_insert_elem_varg__end_insert_1000_multiple),\
    UT_CASE_BEGIN(_basic_string_range_replace_elem__basic_string_range_replace_elem_varg,\
        test__basic_string_range_replace_elem__basic_string_range_replace_elem_varg__null_container),\
    UT_CASE(test__basic_string_range_replace_elem__basic_string_range_replace_elem_varg__non_inited_container),\
    UT_CASE(test__basic_string_range_replace_elem__basic_string_range_replace_elem_varg__invalid_range),\
    UT_CASE(test__basic_string_range_replace_elem__basic_string_range_replace_elem_varg__empty_replace_empty),\
    UT_CASE(test__basic_string_range_replace_elem__basic_string_range_replace_elem_varg__empty_replace_non_empty),\
    UT_CASE(test__basic_string_range_replace_elem__basic_string_range_replace_elem_varg__begin_replace_empty),\
    UT_CASE(test__basic_string_range_replace_elem__basic_string_range_replace_elem_varg__begin_replace_less),\
    UT_CASE(test__basic_string_range_replace_elem__basic_string_range_replace_elem_varg__begin_replace_equal),\
    UT_CASE(test__basic_string_range_replace_elem__basic_string_range_replace_elem_varg__begin_replace_greater),\
    UT_CASE(test__basic_string_range_replace_elem__basic_string_range_replace_elem_varg__middle_replace_empty),\
    UT_CASE(test__basic_string_range_replace_elem__basic_string_range_replace_elem_varg__middle_replace_less),\
    UT_CASE(test__basic_string_range_replace_elem__basic_string_range_replace_elem_varg__middle_replace_equal),\
    UT_CASE(test__basic_string_range_replace_elem__basic_string_range_replace_elem_varg__middle_replace_greater),\
    UT_CASE(test__basic_string_range_replace_elem__basic_string_range_replace_elem_varg__end_replace_empty),\
    UT_CASE(test__basic_string_range_replace_elem__basic_string_range_replace_elem_varg__end_replace_less),\
    UT_CASE(test__basic_string_range_replace_elem__basic_string_range_replace_elem_varg__end_replace_equal),\
    UT_CASE(test__basic_string_range_replace_elem__basic_string_range_replace_elem_varg__end_replace_greater)

#endif /* _UT_CSTL_BASIC_STRING_PRIVATE_H_ */

